### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by kumpfmoritz** [fercook/SciViz#2]
It looks like the example provided for testing the conrec.py code produces incorrect results. The code you provided for stiching the calculated lines together is missing an '< EPSILON' in the striching function. 

I already fixed the issue and made a pull request: https://github.com/fercook/SciViz/pull/1

Wrong Output:
![image](https://github.com/user-attachments/assets/1fe2ad37-cb11-471e-b482-fa8b3ee28261)

Correct Output:
![image](https://github.com/user-attachments/assets/d7d461a7-3dba-47ae-ac87-f96f5531225c)

# Code sample:

```
from elevation_map.conrec.conrec import conrec
import json
import geopandas as gpd
from shapely.geometry import LineString

# conrec example
data = [[0.0, 1.0, 0.0], [1.0, 2.0, 1.0], [0.0, 1.0, 0.0]]
a=conrec(data, [1.0, 2.0, 3.0], [1.0, 2.0, 3.0], [0.5, 1.0, 2.5],"JSON")

data = json.loads(a)

# Initialize lists to store geometries and levels
geometries = []
levels = []

# Loop through each level and paths
for item in data:
    level = item['level']
    for path in item['paths']:
        # Create LineString geometry from path
        line = LineString([(point['x'], point['y']) for point in path])
        geometries.append(line)
        levels.append(level)
display(data)
# Create GeoDataFrame
gdf = gpd.GeoDataFrame({'level': levels, 'geometry': geometries}, crs='EPSG:4326')

# Display the GeoDataFrame
gdf.explore()
```

**Comment by fercook** [comment]
Thank you, merged!
